### ISSUE TITLE
Prevent loss of emails due to Amavis removal

### ISSUE THREAD

**Issue by cloud86robb3rt** [plesk/cloudlinux7to8#15]
We are using Warden anti-spam filter from danami; https://www.danami.com/products/plesk-extensions/warden-antispam-and-virus-protection.  This uses Amavis and Amavis-milter. Currently after the conversion is completed we need to manually reinstall amavis, this seems be similar to the issue; https://github.com/plesk/centos2alma/issues/288. 

It would be nice to check if amavis and amavis-milter is present, and if so reinstall this during the conversion.

**Comment by SandakovMM** [comment]
I have transferred changes from centos2alma in issue #21
