### ISSUE TITLE
yum keeps cloudlinux 8 packages channel after reverting

### ISSUE THREAD

**Issue by SandakovMM** [plesk/cloudlinux7to8#26]
It appears that the CloudLinux Elevate tool changes the package channel to one that provides cloudlinux-release-8 packages. The cloudlinux7to8 tool does not anticipate this change, so if a conversion attempt fails and you run `cloudlinux7to8 --revert`, the yum package manager retains the new channel. Consequently, the next time you run `yum update`, it will install the cloudlinux-release-8 package, leading to an incorrect distribution indication.
To correct this, we need to switch the channel back during the reversion process.

---

**Workaround**
Run `cln-switch-channel -t 7 -o -f` before or immediately after using `cloudlinux7to8 --revert`.

If cloudlinux-release-8 has already been installed:
1. `cln-switch-channel -t 7 -o -f`
2. `rpm -e --nodeps cloudlinux-release`
3. `yum install -y cloudlinux-release-7.9 --releasever=7`
4. `./cloudlinux7to8 --revert`

**Comment by vizovitin** [comment]
The fix will be available in versions > 1.0.2.
